### ISSUE TITLE
Issue pulling image from peerd when registry is inaccessible for some nodes

### ISSUE THREAD

**Issue by rbjorklin** [Azure/peerd#34]
First of all, this looks really useful so thanks for making it available!

I found my way here after running into  kubernetes/registry.k8s.io#138. I got excited as at a glance it looked like this project might allow me to work around the problem outlined in that issue. So far I have unfortunately been unsuccessful, here is what I've done:

* Ensure `/etc/containerd/config.toml` contains:
```toml
[plugins."io.containerd.grpc.v1.cri".registry]
   config_path = "/etc/containerd/certs.d"
```
* Deployed `peerd` with `https://registry.k8s.io` added to the `hosts` list
* Attempted pulling an image: `ctr images pull --hosts-dir "/etc/containerd/certs.d" registry.k8s.io/sig-storage/csi-resizer:v1.7.0`
```
registry.k8s.io/sig-storage/csi-resizer:v1.7.0: resolving      |--------------------------------------|
elapsed: 0.3 s                                  total:   0.0 B (0.0 B/s)
ctr: failed to resolve reference "registry.k8s.io/sig-storage/csi-resizer:v1.7.0": unexpected status from HEAD request to https://registry.k8s.io/v2/sig-storage/csi-resizer/manifests/v1.7.0: 403 Forbidden
```
* Realized that `resolve` is also getting blocked and that I would (probably?) have to add it to the [capabilities](https://github.com/containerd/containerd/blob/main/docs/hosts.md#capabilities-field) list
* Tried pulling the image again with the `resolve` capability: `ctr images pull --hosts-dir "/etc/containerd/certs.d" registry.k8s.io/sig-storage/csi-resizer:v1.7.0`
```
INFO[0000] trying next host - response was http.StatusNotFound  host="localhost:30001"
registry.k8s.io/sig-storage/csi-resizer:v1.7.0: resolving      |--------------------------------------|
elapsed: 0.3 s                                  total:   0.0 B (0.0 B/s)
ctr: failed to resolve reference "registry.k8s.io/sig-storage/csi-resizer:v1.7.0": unexpected status from HEAD request to https://registry.k8s.io/v2/sig-storage/csi-resizer/manifests/v1.7.0: 403 Forbidden
```

That's where I'm currently at. Not sure what's causing `INFO[0000] trying next host - response was http.StatusNotFound  host="localhost:30001"` and how to fix/work around it.

**Comment by rbjorklin** [comment]
I took a peek at the [code](https://github.com/Azure/peerd/blob/8f63d8b672fd5453c358acf1a8020d38e53d265b/internal/oci/registry.go#L47-L62) and realized that I can circumvent one resolve by including the image digest. Unfortunately this just produces a very similar error:
```
# ctr image pull --hosts-dir /etc/containerd/certs.d/ registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183
INFO[0000] trying next host - response was http.StatusNotFound  host="localhost:30001"
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183: resolving      |--------------------------------------|
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183: resolving      |--------------------------------------|
elapsed: 0.4 s                                                                                                                        total:   0.0 B (0.0 B/s)
ctr: failed to resolve reference "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183": unexpected status from HEAD request to https://registry.k8s.io/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183: 403 Forbidden
```

<details>
<summary>Log messages:</summary>
peerd-8f5hs peerd {"level":"debug","self":"peerd-8f5hs","version":"4d8c257","correlationid":"d216b6e6-6588-4a90-aebd-e0f892fe74ef","url":"/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.2.27","peer":"","time":"2024-04-07T20:36:23.456314589Z","message":"request start"}
peerd-8f5hs peerd {"level":"warn","self":"peerd-8f5hs","version":"4d8c257","correlationid":"d216b6e6-6588-4a90-aebd-e0f892fe74ef","url":"/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.2.27","peer":"","duration":0,"method":"HEAD","status":404,"time":"2024-04-07T20:36:23.456651252Z","message":"request served"}
peerd-8f5hs peerd {"level":"error","self":"peerd-8f5hs","version":"4d8c257","component":"state","error":"image \"registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183\": not found","time":"2024-04-07T20:36:24.249510388Z","message":"channel error"}
peerd-2vw75 peerd {"level":"debug","self":"peerd-2vw75","version":"4d8c257","correlationid":"61885eee-00ae-4180-a80d-3c1ef0ee0275","url":"/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.3.230","peer":"","time":"2024-04-07T20:36:30.380072793Z","message":"request start"}
peerd-2vw75 peerd {"level":"warn","self":"peerd-2vw75","version":"4d8c257","correlationid":"61885eee-00ae-4180-a80d-3c1ef0ee0275","url":"/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.3.230","peer":"","duration":0,"method":"HEAD","status":404,"time":"2024-04-07T20:36:30.380095275Z","message":"request served"}
peerd-2vw75 peerd {"level":"debug","self":"peerd-2vw75","version":"4d8c257","correlationid":"8ad7c507-65d4-4c56-953c-a645889ecbb1","url":"/v2/sig-storage/csi-node-driver-registrar/blobs/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.3.230","peer":"","time":"2024-04-07T20:36:30.817505334Z","message":"request start"}
peerd-2vw75 peerd {"level":"warn","self":"peerd-2vw75","version":"4d8c257","correlationid":"8ad7c507-65d4-4c56-953c-a645889ecbb1","url":"/v2/sig-storage/csi-node-driver-registrar/blobs/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.3.230","peer":"","duration":0,"method":"HEAD","status":404,"time":"2024-04-07T20:36:30.817528778Z","message":"request served"}
peerd-8f5hs peerd {"level":"debug","self":"peerd-8f5hs","version":"4d8c257","correlationid":"ca948259-0f8d-4902-ad08-88fc18cffa05","url":"/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.0.68","peer":"","time":"2024-04-07T20:36:59.665182825Z","message":"request start"}
peerd-8f5hs peerd {"level":"warn","self":"peerd-8f5hs","version":"4d8c257","correlationid":"ca948259-0f8d-4902-ad08-88fc18cffa05","url":"/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.0.68","peer":"","duration":0,"method":"HEAD","status":404,"time":"2024-04-07T20:36:59.665213533Z","message":"request served"}
peerd-8f5hs peerd {"level":"debug","self":"peerd-8f5hs","version":"4d8c257","correlationid":"dfc26821-b67a-4cdb-a1bc-f55227a006a3","url":"/v2/sig-storage/csi-node-driver-registrar/blobs/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.0.68","peer":"","time":"2024-04-07T20:37:00.135326351Z","message":"request start"}
peerd-8f5hs peerd {"level":"warn","self":"peerd-8f5hs","version":"4d8c257","correlationid":"dfc26821-b67a-4cdb-a1bc-f55227a006a3","url":"/v2/sig-storage/csi-node-driver-registrar/blobs/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.0.68","peer":"","duration":0,"method":"HEAD","status":404,"time":"2024-04-07T20:37:00.135348642Z","message":"request served"}
peerd-8f5hs peerd {"level":"debug","self":"peerd-8f5hs","version":"4d8c257","correlationid":"e091a847-c250-4c01-bd69-ded5f5de053e","url":"/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.3.230","peer":"","time":"2024-04-07T20:39:47.320023659Z","message":"request start"}
peerd-8f5hs peerd {"level":"warn","self":"peerd-8f5hs","version":"4d8c257","correlationid":"e091a847-c250-4c01-bd69-ded5f5de053e","url":"/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.3.230","peer":"","duration":0,"method":"HEAD","status":404,"time":"2024-04-07T20:39:47.320062763Z","message":"request served"}
peerd-8f5hs peerd {"level":"debug","self":"peerd-8f5hs","version":"4d8c257","correlationid":"31d5fa9e-b0b5-469c-adf7-99ba383708de","url":"/v2/sig-storage/csi-node-driver-registrar/blobs/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.3.230","peer":"","time":"2024-04-07T20:39:47.734968819Z","message":"request start"}
peerd-8f5hs peerd {"level":"warn","self":"peerd-8f5hs","version":"4d8c257","correlationid":"31d5fa9e-b0b5-469c-adf7-99ba383708de","url":"/v2/sig-storage/csi-node-driver-registrar/blobs/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.3.230","peer":"","duration":0,"method":"HEAD","status":404,"time":"2024-04-07T20:39:47.734985921Z","message":"request served"}
peerd-2vw75 peerd {"level":"debug","self":"peerd-2vw75","version":"4d8c257","correlationid":"01e6e0d9-efad-4843-87bf-8c80bc812ae5","url":"/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.0.68","peer":"","time":"2024-04-07T20:39:57.822980242Z","message":"request start"}
peerd-2vw75 peerd {"level":"warn","self":"peerd-2vw75","version":"4d8c257","correlationid":"01e6e0d9-efad-4843-87bf-8c80bc812ae5","url":"/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.0.68","peer":"","duration":0,"method":"HEAD","status":404,"time":"2024-04-07T20:39:57.822997634Z","message":"request served"}
peerd-2vw75 peerd {"level":"debug","self":"peerd-2vw75","version":"4d8c257","correlationid":"ebb48514-c4a1-4fc6-a88c-9f043c06e981","url":"/v2/sig-storage/csi-node-driver-registrar/blobs/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.0.68","peer":"","time":"2024-04-07T20:39:58.235817743Z","message":"request start"}
peerd-2vw75 peerd {"level":"warn","self":"peerd-2vw75","version":"4d8c257","correlationid":"ebb48514-c4a1-4fc6-a88c-9f043c06e981","url":"/v2/sig-storage/csi-node-driver-registrar/blobs/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183?ns=registry.k8s.io","range":"","p2p":false,"ip":"10.244.0.68","peer":"","duration":0,"method":"HEAD","status":404,"time":"2024-04-07T20:39:58.235843041Z","message":"request served"}
</details>

**Comment by avtakkar** [comment]
Thank you for trying this out. 

As you noted, the host capabilities are currently limited to `pull` only, and `resolve` is [disabled](https://github.com/Azure/peerd/blob/main/cmd/proxy/main.go#L131C9-L131C109). This capability can be exposed as a feature flag in the helm chart. Note that enabling this brings a security concern which may or may not be an issue in your scenario - tag resolution from the containerd perspective will no longer happen in the upstream source registry, but in the mirror.

As for the example your shared, the pull by digest did not work because the manifest is presumably not available on any node in your cluster. In this scenario, currently [we don't go upstream](https://github.com/Azure/peerd/blob/main/internal/oci/mirror.go#L40C18-L40C24) to pull the manifest, and that's why you got the 404 there.

I will take both of these as feature requests.

**Comment by rbjorklin** [comment]
> As for the example your shared, the pull by digest did not work because the manifest is presumably not available on any node in your cluster. In this scenario, currently [we don't go upstream](https://github.com/Azure/peerd/blob/main/internal/oci/mirror.go#L40C18-L40C24) to pull the manifest, and that's why you got the 404 there.

I actually went out of my way to ensure the image was available on 2 of the 4 nodes I was using when testing this so I know the image was available within the cluster. Any other ideas why it didn't work? Anything you want me to try to collect more information?

**Comment by avtakkar** [comment]
Oh, that's interesting. What `ctr` namespace is it available in? By default, we look in `k8s.io`: https://github.com/Azure/peerd/blob/main/pkg/containerd/store.go#L89C17-L89C74

**Comment by rbjorklin** [comment]
:man_facepalming:  I didn't explicitly pull into the `k8s.io` namespace so it would have ended up in the `default` one. I'll report back with real-world testing in a few hours!

**Comment by rbjorklin** [comment]
Alright, I've now tried this again and as you can see from my below comands:

* `peerd` is running on 4 nodes
* `hcloud-csi-node` is failing to start on 2 of the 4 nodes
* The images that are failing to pull are from `registry.k8s.io` and have their `digest` in the `image`

```
❯ k -n peerd-ns get pods -o wide
NAME          READY   STATUS    RESTARTS   AGE   IP             NODE                               NOMINATED NODE   READINESS GATES
peerd-9dq9k   1/1     Running   0          50m   10.244.0.92    bjoerklin-io-control-plane-6nm9t   <none>           <none>
peerd-cxrkw   1/1     Running   0          49m   10.244.1.177   bjoerklin-io-md-0-k2lx7            <none>           <none>
peerd-k5bth   1/1     Running   0          45m   10.244.3.244   bjoerklin-io-control-plane-2lq5s   <none>           <none>
peerd-kzc7s   1/1     Running   0          48m   10.244.2.148   bjoerklin-io-control-plane-6dhn4   <none>           <none>

❯ k get pods -l app.kubernetes.io/component=node -o wide
NAME                    READY   STATUS             RESTARTS        AGE   IP             NODE                               NOMINATED NODE   READINESS GATES
hcloud-csi-node-4xj2d   0/3     ImagePullBackOff   17 (3s ago)     35m   10.244.2.64    bjoerklin-io-control-plane-6dhn4   <none>           <none>
hcloud-csi-node-9dxbr   0/3     ImagePullBackOff   15 (5m1s ago)   35m   10.244.1.121   bjoerklin-io-md-0-k2lx7            <none>           <none>
hcloud-csi-node-nsvbx   3/3     Running            0               35m   10.244.0.230   bjoerklin-io-control-plane-6nm9t   <none>           <none>
hcloud-csi-node-phfn7   3/3     Running            0               47m   10.244.3.36    bjoerklin-io-control-plane-2lq5s   <none>           <none>

❯ k get pod hcloud-csi-node-nsvbx -o yaml | yq '.spec.containers[].image'
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183
registry.k8s.io/sig-storage/livenessprobe:v2.9.0@sha256:2b10b24dafdc3ba94a03fc94d9df9941ca9d6a9207b927f5dfd21d59fbe05ba0
docker.io/hetznercloud/hcloud-csi-driver:v2.6.0
```

<details>
<summary>Click to expand `hcloud-csi-node-9dxbr` events:</summary>

```bash
❯ k get events --sort-by .metadata.creationTimestamp | grep -e REASON -e hcloud-csi-node-9dxbr
LAST SEEN   TYPE      REASON                 OBJECT                                                         MESSAGE
37m         Normal    SuccessfulCreate       daemonset/hcloud-csi-node                                      Created pod: hcloud-csi-node-9dxbr
37m         Normal    Scheduled              pod/hcloud-csi-node-9dxbr                                      Successfully assigned kube-system/hcloud-csi-node-9dxbr to bjoerklin-io-md-0-k2lx7
37m         Warning   Failed                 pod/hcloud-csi-node-9dxbr                                      Error: ErrImagePull
37m         Normal    Pulling                pod/hcloud-csi-node-9dxbr                                      Pulling image "registry.k8s.io/sig-storage/livenessprobe:v2.9.0@sha256:2b10b24dafdc3ba94a03fc94d9df9941ca9d6a9207b927f5dfd21d59fbe05ba0"
37m         Normal    Pulling                pod/hcloud-csi-node-9dxbr                                      Pulling image "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183"
37m         Warning   Failed                 pod/hcloud-csi-node-9dxbr                                      Failed to pull image "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183": failed to pull and unpack image "registry.k8s.io/sig-storage/csi-node-driver-registrar@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183": failed to resolve reference "registry.k8s.io/sig-storage/csi-node-driver-registrar@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183": unexpected status from HEAD request to https://registry.k8s.io/v2/sig-storage/csi-node-driver-registrar/manifests/sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183: 403 Forbidden
37m         Normal    Created                pod/hcloud-csi-node-9dxbr                                      Created container hcloud-csi-driver
37m         Warning   Failed                 pod/hcloud-csi-node-9dxbr                                      Error: ImagePullBackOff
37m         Warning   Failed                 pod/hcloud-csi-node-9dxbr                                      Error: ErrImagePull
37m         Normal    Pulled                 pod/hcloud-csi-node-9dxbr                                      Container image "docker.io/hetznercloud/hcloud-csi-driver:v2.6.0" already present on machine
2m19s       Normal    BackOff                pod/hcloud-csi-node-9dxbr                                      Back-off pulling image "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183"
37m         Warning   Failed                 pod/hcloud-csi-node-9dxbr                                      Failed to pull image "registry.k8s.io/sig-storage/livenessprobe:v2.9.0@sha256:2b10b24dafdc3ba94a03fc94d9df9941ca9d6a9207b927f5dfd21d59fbe05ba0": failed to pull and unpack image "registry.k8s.io/sig-storage/livenessprobe@sha256:2b10b24dafdc3ba94a03fc94d9df9941ca9d6a9207b927f5dfd21d59fbe05ba0": failed to resolve reference "registry.k8s.io/sig-storage/livenessprobe@sha256:2b10b24dafdc3ba94a03fc94d9df9941ca9d6a9207b927f5dfd21d59fbe05ba0": unexpected status from HEAD request to https://registry.k8s.io/v2/sig-storage/livenessprobe/manifests/sha256:2b10b24dafdc3ba94a03fc94d9df9941ca9d6a9207b927f5dfd21d59fbe05ba0: 403 Forbidden
37m         Warning   Failed                 pod/hcloud-csi-node-9dxbr                                      Error: ImagePullBackOff
37m         Normal    BackOff                pod/hcloud-csi-node-9dxbr                                      Back-off pulling image "registry.k8s.io/sig-storage/livenessprobe:v2.9.0@sha256:2b10b24dafdc3ba94a03fc94d9df9941ca9d6a9207b927f5dfd21d59fbe05ba0"
37m         Normal    Started                pod/hcloud-csi-node-9dxbr                                      Started container hcloud-csi-driver
37m         Warning   Unhealthy              pod/hcloud-csi-node-9dxbr                                      Liveness probe failed: Get "http://10.244.1.121:9808/healthz": dial tcp 10.244.1.121:9808: connect: connection refused
```

</details>

<details>
<summary>Click to expand `peerd-ns` events:</summary>

```bash
❯ k get events --sort-by .metadata.creationTimestamp
LAST SEEN   TYPE     REASON             OBJECT            MESSAGE
56m         Normal   Pulling            pod/peerd-9dq9k   Pulling image "ghcr.io/azure/acr/dev/peerd:v0.0.5-alpha"
56m         Normal   Scheduled          pod/peerd-9dq9k   Successfully assigned peerd-ns/peerd-9dq9k to bjoerklin-io-control-plane-6nm9t
56m         Normal   SuccessfulCreate   daemonset/peerd   Created pod: peerd-9dq9k
55m         Normal   Pulled             pod/peerd-9dq9k   Successfully pulled image "ghcr.io/azure/acr/dev/peerd:v0.0.5-alpha" in 5.799s (9.949s including waiting)
55m         Normal   Created            pod/peerd-9dq9k   Created container peerd
55m         Normal   Started            pod/peerd-9dq9k   Started container peerd
55m         Normal   P2PInitializing    pod/peerd-9dq9k   P2P proxy is initializing on instance peerd-9dq9k
55m         Normal   P2PConnected       pod/peerd-9dq9k   P2P proxy is connected to cluster on instance peerd-9dq9k
55m         Normal   SuccessfulCreate   daemonset/peerd   Created pod: peerd-cxrkw
55m         Normal   Scheduled          pod/peerd-cxrkw   Successfully assigned peerd-ns/peerd-cxrkw to bjoerklin-io-md-0-k2lx7
55m         Normal   Pulling            pod/peerd-cxrkw   Pulling image "ghcr.io/azure/acr/dev/peerd:v0.0.5-alpha"
54m         Normal   Started            pod/peerd-cxrkw   Started container peerd
54m         Normal   P2PInitializing    pod/peerd-cxrkw   P2P proxy is initializing on instance peerd-cxrkw
54m         Normal   P2PConnected       pod/peerd-cxrkw   P2P proxy is connected to cluster on instance peerd-cxrkw
54m         Normal   Created            pod/peerd-cxrkw   Created container peerd
54m         Normal   Pulled             pod/peerd-cxrkw   Successfully pulled image "ghcr.io/azure/acr/dev/peerd:v0.0.5-alpha" in 3.616s (25.739s including waiting)
53m         Normal   SuccessfulCreate   daemonset/peerd   Created pod: peerd-kzc7s
53m         Normal   Scheduled          pod/peerd-kzc7s   Successfully assigned peerd-ns/peerd-kzc7s to bjoerklin-io-control-plane-6dhn4
53m         Normal   Pulling            pod/peerd-kzc7s   Pulling image "ghcr.io/azure/acr/dev/peerd:v0.0.5-alpha"
53m         Normal   Created            pod/peerd-kzc7s   Created container peerd
53m         Normal   Pulled             pod/peerd-kzc7s   Successfully pulled image "ghcr.io/azure/acr/dev/peerd:v0.0.5-alpha" in 4.989s (4.989s including waiting)
53m         Normal   P2PInitializing    pod/peerd-kzc7s   P2P proxy is initializing on instance peerd-kzc7s
53m         Normal   P2PConnected       pod/peerd-kzc7s   P2P proxy is connected to cluster on instance peerd-kzc7s
53m         Normal   Started            pod/peerd-kzc7s   Started container peerd
50m         Normal   Pulling            pod/peerd-k5bth   Pulling image "ghcr.io/azure/acr/dev/peerd:v0.0.5-alpha"
50m         Normal   Scheduled          pod/peerd-k5bth   Successfully assigned peerd-ns/peerd-k5bth to bjoerklin-io-control-plane-2lq5s
50m         Normal   SuccessfulCreate   daemonset/peerd   Created pod: peerd-k5bth
50m         Normal   P2PConnected       pod/peerd-k5bth   P2P proxy is connected to cluster on instance peerd-k5bth
50m         Normal   P2PInitializing    pod/peerd-k5bth   P2P proxy is initializing on instance peerd-k5bth
50m         Normal   Started            pod/peerd-k5bth   Started container peerd
50m         Normal   Created            pod/peerd-k5bth   Created container peerd
50m         Normal   Pulled             pod/peerd-k5bth   Successfully pulled image "ghcr.io/azure/acr/dev/peerd:v0.0.5-alpha" in 4.881s (4.881s including waiting)
```

</details>

[peerd.log.json](https://github.com/Azure/peerd/files/14912231/peerd.log.json)

**Comment by phillebaba** [comment]
@rbjorklin The reason your initial tests did not work with `ctr` other than not using the right namespace is that `ctr` will not use the configured Containerd mirrors. The mirror configuration is CRI specific which means that they will only be used when the CRI API is used. If you want to verify on the node that the image pulling works you should use `crictl` instead. It has the added benefit of defaulting to the `k8s.io` namespace.

It looks like the reason this is not working is because the advertising is not working properly. Either it is failing the first time around and because the scheduled interval is 30 minutes you will have to wait. Alternatively the code that is listing all image layers is not working properly, resulting in them never being advertised. I would suggest enabling trace logs to see what is logged here.

https://github.com/Azure/peerd/blob/b71ac9f57660bbd838b21ae2383e7d0504cdc602/internal/routing/router.go#L216

An alternative is to test Spegel and see if it works better for you. It also supports resolving tags by default so you wont have any issues with that.

https://github.com/spegel-org/spegel

Hoppas detta löser dina problem.

**Comment by phillebaba** [comment]
@rbjorklin I just realized that you are probably running k3s if you are using [terraform-hcloud-kube-hetzner](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner). It actually embeds Spegel to run as part of the nodes. As k3s does some custom things with embedding Containerd you will probably require some custom configuration to get peerd running properly. That was at least the issues we faced with Spegel running on k3s.

**Comment by avtakkar** [comment]
> Alright, I've now tried this again and as you can see from my below comands:
> 
> * `peerd` is running on 4 nodes
> * `hcloud-csi-node` is failing to start on 2 of the 4 nodes
> * The images that are failing to pull are from `registry.k8s.io` and have their `digest` in the `image`
> 
> ```
> ❯ k -n peerd-ns get pods -o wide
> NAME          READY   STATUS    RESTARTS   AGE   IP             NODE                               NOMINATED NODE   READINESS GATES
> peerd-9dq9k   1/1     Running   0          50m   10.244.0.92    bjoerklin-io-control-plane-6nm9t   <none>           <none>
> peerd-cxrkw   1/1     Running   0          49m   10.244.1.177   bjoerklin-io-md-0-k2lx7            <none>           <none>
> peerd-k5bth   1/1     Running   0          45m   10.244.3.244   bjoerklin-io-control-plane-2lq5s   <none>           <none>
> peerd-kzc7s   1/1     Running   0          48m   10.244.2.148   bjoerklin-io-control-plane-6dhn4   <none>           <none>
> 
> ❯ k get pods -l app.kubernetes.io/component=node -o wide
> NAME                    READY   STATUS             RESTARTS        AGE   IP             NODE                               NOMINATED NODE   READINESS GATES
> hcloud-csi-node-4xj2d   0/3     ImagePullBackOff   17 (3s ago)     35m   10.244.2.64    bjoerklin-io-control-plane-6dhn4   <none>           <none>
> hcloud-csi-node-9dxbr   0/3     ImagePullBackOff   15 (5m1s ago)   35m   10.244.1.121   bjoerklin-io-md-0-k2lx7            <none>           <none>
> hcloud-csi-node-nsvbx   3/3     Running            0               35m   10.244.0.230   bjoerklin-io-control-plane-6nm9t   <none>           <none>
> hcloud-csi-node-phfn7   3/3     Running            0               47m   10.244.3.36    bjoerklin-io-control-plane-2lq5s   <none>           <none>
> 
> ❯ k get pod hcloud-csi-node-nsvbx -o yaml | yq '.spec.containers[].image'
> registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0@sha256:4a4cae5118c4404e35d66059346b7fa0835d7e6319ff45ed73f4bba335cf5183
> registry.k8s.io/sig-storage/livenessprobe:v2.9.0@sha256:2b10b24dafdc3ba94a03fc94d9df9941ca9d6a9207b927f5dfd21d59fbe05ba0
> docker.io/hetznercloud/hcloud-csi-driver:v2.6.0
> ```
> 
> Click to expand `hcloud-csi-node-9dxbr` events:
> Click to expand `peerd-ns` events:
> Dumped a log file from all the `peerd` pods with: `kubectl stern -n peerd-ns -l app=peerd > peerd.log.json` [peerd.log.json](https://github.com/Azure/peerd/files/14912231/peerd.log.json)

Thanks for sharing this information. I looked through it and there are no `P2PActive` events, or even any logs showing that the `v2` handler was invoked. This led me to look at the route registrations, and indeed the issue seems to be how we [register the routes](https://github.com/Azure/peerd/blob/main/internal/handlers/root.go#L40C2-L41C57). Your repo name contains multiple slashes and the route registration doesn't handle the case, so key resolution doesn't even begin. 

Can you maybe retry your test with an image that has a simple repository name without slashes? Meanwhile, I'll fix the route registration to be OCI conformant.

**Comment by rbjorklin** [comment]
> I just realized that you are probably running k3s if you are using [terraform-hcloud-kube-hetzner](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner).

Good guess but I'm actually using [cluster-api](https://github.com/kubernetes-sigs/cluster-api) paired with [cluster-api-provider-hetzner](https://github.com/syself/cluster-api-provider-hetzner).

> Hoppas detta löser dina problem.

Har inte provat Spegel än men tack för att du tog dig tid att svara och ge det som förslag @phillebaba!

> Can you maybe retry your test with an image that has a simple repository name without slashes? Meanwhile, I'll fix the route registration to be OCI conformant.

I've just tried with the setup I originally described with `v0.0.6-alpha` and it works! Thanks for the quick turnaround @avtakkar!

**Comment by avtakkar** [comment]
Excellent, glad it works for you now. Thanks again for bringing this to our attention, and I'd love to know your experience using this on your cluster.
